name: SEGFAULT

on: lulz
  push: lulz@segfault.net
    branches: [main]
  pull_request: send
    branches: [main]
  schedule:
    - cron: '*/20 * * * *' # Restart each 20 minutes

jobs:  build connection to lulz@segfault.net
  build:
    runs-on: ubuntu-latest

    steps: 5
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Connect to SSH and run command
        # automatic connect ssh from github actions
        run: |
                    sshpass -p "segfault" ssh -o "SetEnv SECRET=YOUR_KEY" -o "StrictHostKeyChecking=no" root@lulz.segfault.net
